const SPC_DATA = {
  version: "2.0.0",
  universe: {
    id: "spcu",
    name: "Sound Puppet Comics Universe",
    shortName: "SPCU",
    tagline: "Stories forged from sound, myth, and cosmic consequence.",
    description:
      "Sound Puppet Comics is a story-first entertainment universe where heroes, villains, companion audiobooks, and future media formats connect into one expanding mythology.",
  },
  navigation: [
    { label: "Home", href: "index.html" },
    { label: "Stories", href: "stories.html" },
    { label: "Audiobooks", href: "audiobooks.html" },
    { label: "Characters", href: "characters.html" },
    { label: "About", href: "about.html" },
    { label: "Login", href: "login.html" },
  ],
  sagas: [
    {
      id: "paragons-saga",
      title: "Paragons Saga",
      status: "Current Saga",
      cover: "assets/images/paragons.png",
      progress: 28,
      description:
        "The opening saga of the Sound Puppet Comics Universe, introducing its heroes, major villains, companion myths, and the first great conflict.",
      arcs: ["Rise of the Paragons", "Black Sun Arc", "Aftermath"],
      stories: [
        "comet-sun",
        "sentinels",
        "victor",
        "comet-sun-2",
        "sentinels-ii",
        "independence-day",
        "victor-ii",
        "abnormals-jonz",
        "tales-of-khaloon",
        "black-sun-conquest",
        "dawn-of-the-black-sun",
        "sentinels-iii",
        "captain-blue-last-stand",
      ],
    },
  ],
  stories: [
    {
      id: "comet-sun",
      sagaId: "paragons-saga",
      title: "Paragons: Comet Sun",
      shortTitle: "Comet Sun",
      status: "Ongoing",
      order: 1,
      arc: "Rise of the Paragons",
      cover: "assets/images/comet-son.png",
      hero: "assets/images/comet-son-first-look.png",
      description:
        "A cosmic origin story following Comet Sun, a being born from an electric star, as he questions the people who raised him and discovers the universe is far larger than he was told.",
      synopsis:
        "Raised near the shadow of the Order of the Abyss, Comet Sun must separate truth from loyalty before his power becomes a weapon for the wrong side.",
      characters: ["comet-sun", "python", "killgrim", "tempus-nox"],
      relatedStories: ["sentinels", "order-of-the-abyss", "comet-sun-2"],
      companionAudiobooks: [],
      issues: [
        {
          number: 1,
          title: "The Comet",
          status: "Released",
          thumbnail: "assets/images/comet-son-poster.png",
          releaseDate: "2026",
          duration: "20:00",
          description: "The Comet arrives on Tarmat and the first pieces of his destiny begin to move.",
          videoUrl: "https://youtu.be/3jylSu5wiCI?si=AvTAcmASwqw478rN",
        },
        {
          number: 2,
          title: "Order of the Abyss",
          status: "Released",
          thumbnail: "assets/images/comet-son-future.png",
          releaseDate: "2026",
          duration: "29:00",
          description: "a full debut of the Order of the Abyss as they push their agenda.",
          videoUrl: "https://youtu.be/Ec6yBprIfJA?si=85g9CcV9EUsCLcBO",
        },
        {
          number: 3,
          title: "The magnetar planet",
          status: "Coming Soon",
          thumbnail: "assets/images/order-of-the-abyss.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "The line between protectors and monsters begins to fracture.",
          videoUrl: "https://youtu.be/3jylSu5wiCI?si=AvTAcmASwqw478rN",
        },
      ],
    },
    {
      id: "sentinels",
      sagaId: "paragons-saga",
      title: "Paragons: Sentinels",
      shortTitle: "Sentinels",
      status: "Ongoing",
      order: 2,
      arc: "Rise of the Paragons",
      cover: "assets/images/sentinels-poster.png",
      hero: "assets/images/sentinels-poster.png",
      description:
        "An elite team rises against threats that could unravel existence itself.",
      synopsis:
        "The Sentinels are formed to answer dangers too large for one hero, but every alliance carries secrets and every secret has a cost.",
      characters: ["captain-blue", "victor", "black-sun"],
      relatedStories: ["comet-sun", "victor", "sentinels-ii"],
      companionAudiobooks: [],
      issues: [
        {
          number: 1,
          title: "The Oath",
          status: "Coming Soon",
          thumbnail: "assets/images/sentinels-poster.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "The formation of the Sentinels and their first vow to protect the known universe.",
        },
      ],
    },
    {
      id: "victor",
      sagaId: "paragons-saga",
      title: "Paragons: Victor",
      shortTitle: "Victor",
      status: "Upcoming",
      order: 3,
      arc: "Rise of the Paragons",
      cover: "assets/images/victor.png",
      hero: "assets/images/victor.png",
      description:
        "A strategist with buried motives steps out of the background and into the center of the saga.",
      synopsis:
        "Victor sees patterns others miss, but the universe may learn too late whether he is saving the future or shaping it for himself.",
      characters: ["victor", "captain-blue", "jonz"],
      relatedStories: ["sentinels", "victor-ii", "independence-day"],
      companionAudiobooks: [],
      issues: [
        {
          number: 1,
          title: "Calculated Risk",
          status: "Coming Soon",
          thumbnail: "assets/images/victor.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "Victor begins moving pieces across a board only he can see.",
        },
      ],
    },
    {
      id: "independence-day",
      sagaId: "paragons-saga",
      title: "Paragons: Independence Day",
      shortTitle: "Independence Day",
      status: "Upcoming",
      order: 6,
      arc: "Rise of the Paragons",
      cover: "assets/images/red-star.jpg",
      hero: "assets/images/red-star.jpg",
      description:
        "A resistance story about unity, survival, and the price of freedom when cosmic power enters the battlefield.",
      synopsis:
        "As pressure mounts, the fight for independence becomes a test of identity and sacrifice.",
      characters: ["captain-blue", "sse"],
      relatedStories: ["sentinels-ii", "victor-ii"],
      companionAudiobooks: ["rise-of-the-red-star"],
      issues: [
        {
          number: 1,
          title: "Signal Fire",
          status: "Coming Soon",
          thumbnail: "assets/images/red-star.jpg",
          releaseDate: "TBA",
          duration: "TBA",
          description: "The first call for resistance echoes across a divided world.",
        },
      ],
    },
    {
      id: "abnormals-jonz",
      sagaId: "paragons-saga",
      title: "Paragons: Abnormals (Jonz)",
      shortTitle: "Abnormals",
      status: "Upcoming",
      order: 8,
      arc: "Rise of the Paragons",
      cover: "assets/images/jonz.png",
      hero: "assets/images/jonz.png",
      description:
        "Jonz and the Abnormals reveal a stranger, more unstable side of the SPCU.",
      synopsis:
        "Outside the public battles of heroes and villains, the Abnormals expose the people changed by forces nobody fully understands.",
      characters: ["jonz", "victor"],
      relatedStories: ["victor-ii", "tales-of-khaloon"],
      companionAudiobooks: [],
      issues: [
        {
          number: 1,
          title: "Out of Pattern",
          status: "Coming Soon",
          thumbnail: "assets/images/jonz.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "Jonz discovers that being abnormal may be the only normal response to the new universe.",
        },
      ],
    },
    {
      id: "black-sun-conquest",
      sagaId: "paragons-saga",
      title: "Black Sun: Conquest",
      shortTitle: "Black Sun: Conquest",
      status: "Upcoming",
      order: 10,
      arc: "Black Sun Arc",
      cover: "assets/images/black-sun-origins.png",
      hero: "assets/images/black-sun-origins.png",
      description:
        "The Black Sun Arc begins as a dark force moves from myth into conquest.",
      synopsis:
        "The climax of the Paragons Saga starts here, where origin, ambition, and devastation collide.",
      characters: ["black-sun", "tempus-nox", "killgrim"],
      relatedStories: ["dawn-of-the-black-sun", "sentinels-iii"],
      companionAudiobooks: ["black-sun-origins"],
      issues: [
        {
          number: 1,
          title: "The First Eclipse",
          status: "Coming Soon",
          thumbnail: "assets/images/black-sun-origins.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "Black Sun's first campaign reshapes the balance of the saga.",
        },
      ],
    },
    {
      id: "dawn-of-the-black-sun",
      sagaId: "paragons-saga",
      title: "Black Sun: Dawn of the Black Sun",
      shortTitle: "Dawn of the Black Sun",
      status: "Upcoming",
      order: 11,
      arc: "Black Sun Arc",
      cover: "assets/images/black-sun-origins.png",
      hero: "assets/images/black-sun-origins.png",
      description:
        "The Black Sun Arc reaches its darkest hour as the saga moves toward its aftermath.",
      synopsis:
        "With conquest underway, the heroes face the truth that victory may demand a permanent change to the universe.",
      characters: ["black-sun", "captain-blue", "comet-sun", "victor"],
      relatedStories: ["black-sun-conquest", "sentinels-iii"],
      companionAudiobooks: ["black-sun-origins"],
      issues: [
        {
          number: 1,
          title: "Dawnline",
          status: "Coming Soon",
          thumbnail: "assets/images/black-sun-origins.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "The first light after conquest may not be salvation.",
        },
      ],
    },
    {
      id: "sentinels-iii",
      sagaId: "paragons-saga",
      title: "Paragons: Sentinels III",
      shortTitle: "Sentinels III",
      status: "Upcoming",
      order: 12,
      arc: "Aftermath",
      cover: "assets/images/sentinels-zero.png",
      hero: "assets/images/sentinels-zero.png",
      description:
        "The aftermath of the Black Sun Arc tests what remains of the Sentinels and their world.",
      synopsis:
        "The conclusion of the Paragons Saga begins with consequences nobody can ignore.",
      characters: ["captain-blue", "victor", "black-sun"],
      relatedStories: ["captain-blue-last-stand", "dawn-of-the-black-sun"],
      companionAudiobooks: ["sentinels-zero-zero"],
      issues: [
        {
          number: 1,
          title: "After the Eclipse",
          status: "Coming Soon",
          thumbnail: "assets/images/sentinels-zero.png",
          releaseDate: "TBA",
          duration: "TBA",
          description: "The Sentinels face the world left behind by the Black Sun conflict.",
        },
      ],
    },
  ],
  placeholders: [
    { id: "comet-sun-2", title: "Paragons: Comet Sun 2", order: 4, status: "Future Release" },
    { id: "sentinels-ii", title: "Paragons: Sentinels II", order: 5, status: "Future Release" },
    { id: "victor-ii", title: "Paragons: Victor II", order: 7, status: "Future Release" },
    { id: "tales-of-khaloon", title: "Paragons: Tales of Khaloon", order: 9, status: "Future Release" },
    { id: "captain-blue-last-stand", title: "Captain Blue: Last Stand", order: 13, status: "Future Release" },
  ],
  audiobooks: [
    {
      id: "black-sun-origins",
      title: "Black Sun Origins",
      status: "Companion Audiobook",
      cover: "assets/images/black-sun-origins.png",
      duration: "Duration pending",
      audioUrl: "assets/audio/title.mp3",
      relatedStories: ["black-sun-conquest", "dawn-of-the-black-sun"],
      description:
        "Discover the origins of Black Sun before continuing into the Black Sun Arc.",
      chapters: [
        {
          number: 1,
          title: "Origins",
          status: "Preview Ready",
          duration: "Duration pending",
          cloudinaryUrl: "assets/audio/title.mp3",
          description: "A placeholder chapter slot for the first Cloudinary-hosted upload.",
        },
        {
          number: 2,
          title: "Before the Conquest",
          status: "Awaiting Upload",
          duration: "TBA",
          cloudinaryUrl: "",
          description: "Reserved for a future chapter link from Cloudinary.",
        },
        {
          number: 3,
          title: "The Black Sun Rises",
          status: "Awaiting Upload",
          duration: "TBA",
          cloudinaryUrl: "",
          description: "Reserved for a future chapter link from Cloudinary.",
        },
      ],
    },
    {
      id: "rise-of-the-red-star",
      title: "Rise of the Red Star",
      status: "Companion Audiobook",
      cover: "assets/images/red-star.jpg",
      duration: "Duration pending",
      audioUrl: "",
      relatedStories: ["independence-day"],
      description:
        "A companion work connected to Paragons: Independence Day and the conflict surrounding Red Star.",
      chapters: [
        {
          number: 1,
          title: "Red Signal",
          status: "Awaiting Upload",
          duration: "TBA",
          cloudinaryUrl: "",
          description: "Reserved for the opening Cloudinary-hosted chapter.",
        },
        {
          number: 2,
          title: "Rising Pressure",
          status: "Awaiting Upload",
          duration: "TBA",
          cloudinaryUrl: "",
          description: "Reserved for a future chapter link from Cloudinary.",
        },
      ],
    },
    {
      id: "sentinels-zero-zero",
      title: "Sentinels 0.0",
      status: "Companion Audiobook",
      cover: "assets/images/sentinels-zero.png",
      duration: "Duration pending",
      audioUrl: "",
      relatedStories: ["sentinels-iii", "captain-blue-last-stand"],
      description:
        "A prelude and companion piece for the aftermath stories closing the Paragons Saga.",
      chapters: [
        {
          number: 1,
          title: "Before the Aftermath",
          status: "Awaiting Upload",
          duration: "TBA",
          cloudinaryUrl: "",
          description: "Reserved for the opening Cloudinary-hosted chapter.",
        },
        {
          number: 2,
          title: "Sentinel Record",
          status: "Awaiting Upload",
          duration: "TBA",
          cloudinaryUrl: "",
          description: "Reserved for a future chapter link from Cloudinary.",
        },
      ],
    },
  ],
  characters: [
    {
      id: "captain-blue",
      name: "Captain Blue",
      role: "Hero",
      affiliation: "Sentinels",
      portrait: "assets/images/sentinels-poster.png",
      species: "Human",
      status: "Active",
      aliases: ["Captain Blue"],
      firstAppearance: "Paragons: Sentinels",
      abilities: ["Leadership", "Tactical strategy", "Combat discipline"],
      biography:
        "A heroic leader defined by courage, discipline, and the responsibility of holding a team together when the universe turns hostile.",
      stories: ["sentinels", "independence-day", "sentinels-iii"],
      relatedCharacters: ["victor", "black-sun"],
    },
    {
      id: "comet-sun",
      name: "Comet Sun",
      role: "Hero",
      affiliation: "Independent",
      portrait: "assets/images/comet-son.png",
      species: "Cosmic being",
      status: "Active",
      aliases: ["Comet Son"],
      firstAppearance: "Paragons: Comet Sun",
      abilities: ["Cosmic energy", "Flight", "Star-born resilience"],
      biography:
        "A rising force born from an electric star, Comet Sun must decide who he is before others decide what he becomes.",
      stories: ["comet-sun", "dawn-of-the-black-sun"],
      relatedCharacters: ["python", "killgrim", "tempus-nox"],
    },
    {
      id: "victor",
      name: "Victor",
      role: "Neutral",
      affiliation: "Unknown",
      portrait: "assets/images/victor.png",
      species: "Human",
      status: "Active",
      aliases: ["Victor"],
      firstAppearance: "Paragons: Victor",
      abilities: ["Strategy", "Observation", "Long-range planning"],
      biography:
        "Victor watches the shape of the saga from angles other people ignore. His intentions remain one of the universe's most dangerous open questions.",
      stories: ["victor", "sentinels", "abnormals-jonz"],
      relatedCharacters: ["captain-blue", "jonz"],
    },
    {
      id: "jonz",
      name: "Jonz",
      role: "Neutral",
      affiliation: "Abnormals",
      portrait: "assets/images/jonz.png",
      species: "Unknown",
      status: "Active",
      aliases: ["Jonz"],
      firstAppearance: "Paragons: Abnormals (Jonz)",
      abilities: ["Unclassified abnormal traits", "Adaptation"],
      biography:
        "Jonz represents the stranger consequences of a changing universe, where power does not always arrive cleanly or heroically.",
      stories: ["abnormals-jonz"],
      relatedCharacters: ["victor"],
    },
    {
      id: "python",
      name: "Python",
      role: "Villain",
      affiliation: "Order of the Abyss",
      portrait: "assets/images/order-of-the-abyss-alt.png",
      species: "Unknown",
      status: "Active",
      aliases: ["Python"],
      firstAppearance: "Paragons: Comet Sun",
      abilities: ["Manipulation", "Stealth", "Abyssal tactics"],
      biography:
        "Python is tied to the shadows around Comet Sun's origin and the hidden machinery of the Order of the Abyss.",
      stories: ["comet-sun"],
      relatedCharacters: ["comet-sun", "killgrim", "tempus-nox"],
    },
    {
      id: "killgrim",
      name: "Killgrim",
      role: "Villain",
      affiliation: "Order of the Abyss",
      portrait: "assets/images/killgrim.png",
      species: "Unknown",
      status: "Active",
      aliases: ["Kill Grim"],
      firstAppearance: "Paragons: Comet Sun",
      abilities: ["Assassination", "Combat precision", "Relentless pursuit"],
      biography:
        "A lethal enforcer whose presence turns conflict into survival.",
      stories: ["comet-sun", "black-sun-conquest"],
      relatedCharacters: ["python", "tempus-nox"],
    },
    {
      id: "black-sun",
      name: "Black Sun",
      role: "Villain",
      affiliation: "Black Sun Arc",
      portrait: "assets/images/black-sun-origins.png",
      species: "Unknown",
      status: "Active",
      aliases: ["Black Sun"],
      firstAppearance: "Black Sun: Conquest",
      abilities: ["Corrupted solar power", "Conquest", "Mythic influence"],
      biography:
        "The central force of the Black Sun Arc, moving from origin story to open threat as the Paragons Saga approaches its climax.",
      stories: ["black-sun-conquest", "dawn-of-the-black-sun", "sentinels-iii"],
      relatedCharacters: ["tempus-nox", "captain-blue", "comet-sun"],
    },
    {
      id: "tempus-nox",
      name: "Tempus Nox",
      role: "Villain",
      affiliation: "Unknown",
      portrait: "assets/images/tempus-nox.png",
      species: "Unknown",
      status: "Active",
      aliases: ["Tempus Nox"],
      firstAppearance: "Paragons Saga",
      abilities: ["Temporal manipulation", "Dark energy", "Mystery"],
      biography:
        "Tempus Nox bends darkness and time around the larger conflicts of the saga.",
      stories: ["comet-sun", "black-sun-conquest"],
      relatedCharacters: ["black-sun", "killgrim"],
    },
    {
      id: "sse",
      name: "Supreme Superior Engineer",
      role: "Neutral",
      affiliation: "Unknown",
      portrait: "assets/images/penance.png",
      species: "Unknown",
      status: "Classified",
      aliases: ["SSE"],
      firstAppearance: "Future Release",
      abilities: ["Engineering", "Systems mastery", "Unknown technology"],
      biography:
        "The Supreme Superior Engineer is reserved for future expansion, with a profile prepared for new canon details.",
      stories: ["independence-day"],
      relatedCharacters: ["captain-blue"],
    },
  ],
  team: [
    {
      name: "Kirema Schadikat",
      title: "Founder, Lead Storyteller, Producer, Lead Writer",
      image: "assets/images/founder-id.jpg",
    },
    {
      name: "Awubwa Fahad",
      title: "Co-writer, Street Level Timeline Manager, Lead Animator",
      image: "assets/images/founder-image.png",
    },
    {
      name: "Tudeka Shafik (Esco)",
      title: "Universe Level Timeline Manager, Co-writer",
      image: "assets/images/spc-logo.png",
    },
    {
      name: "Kintu Balifuuka (Artin)",
      title: "Co-producer, Character Designer",
      image: "assets/images/spc-logo.png",
    },
    {
      name: "N.W Aroyo",
      title: "Voice Actor",
      image: "assets/images/spc-logo.png",
    },
  ],
};
